accumulation_step: 8
adam_beta1: 0.9
adam_beta2: 0.999
batch_size: 32
data_dir: ./dataset/BGL
dataset_name: BGL
device: cpu
dim_feedforward: 2048
dim_model: 300
dropout: 0.1
embedding_dim: 300
embeddings: embeddings_average.json
epsilon: 1.0e-08
hidden_size: 128
history_size: 10
is_chronological: true
log_file: BGL.log
lr: 0.001
max_epoch: 10
model_name: DeepLog
n_class: 2
num_encoder_layers: 1
num_heads: 8
num_layers: 2
optim_momentum: 0.9
optimizer: adamw
output_dir: ./output/
quantitative: false
resume_path: false
scheduler: linear
semantic: false
sequential: true
session_level: entry
step_size: 20
topk: 9
train_size: 0.1
valid_ratio: 0.1
warmup_rate: 0.1
weight_decay: 0.1
window_size: 20
grouping: session
